### ISSUE TITLE
Cursor animations conflict with `"editor.minimap.enabled": false`

### ISSUE THREAD

**Issue by Seng-Jik** [BrandonKirbyson/VSCode-Animations#12] opened 2023-06-12 02:52 UTC
Cursor animations will disabled when `"editor.minimap.enabled": false` was set.

**Comment by BrandonKirbyson** [comment] 2023-06-12 15:57
Thank you for helping find the cause for this issue. It is now fixed with newest version `1.0.10`.

**Closed by BrandonKirbyson** 2023-06-12 15:57 UTC
Labels: bug
