### ISSUE TITLE
Closing tab animation

### ISSUE THREAD

**Issue by Emarrest** [BrandonKirbyson/VSCode-Animations#8] opened 2023-06-02 09:49 UTC
currently when you open a new tab you get the nice pop animation, but when you close it there is no animation, it just disappears.
it would be nice to have a closing pop animation

**Comment by BrandonKirbyson** [comment] 2023-08-13 16:25
Sorry for never adding this but for now I probably will not. The problem is vscode deletes elements for tabs and you cannot apply an animation on delete unless you use some custom javascript and catch the deletion. I tested the basics of that and vscode messes up detecting the "deleted" elements as tabs and it just gets messy quick. Maybe in the future or if anyone has ideas on this then I will add closing animations but for now I think it is better to not introduce a bunch of bugs.

**Closed by BrandonKirbyson** 2023-08-13 16:25 UTC
Labels: wontfix, animation

**Comment by Emarrest** [comment] 2023-08-13 16:42
Not a problem, thank you for your time and keep it up!
