### ISSUE TITLE
The Animation doesn't work in Fedora 39

### ISSUE THREAD

**Issue by cycode0527** [BrandonKirbyson/VSCode-Animations#42] opened 2024-01-01 09:59 UTC
My system is Fedora 39, new installed yesterday.
Now I installed this plugin,use default settings.
BUT......
Any animation don't work!
Follows are the images--I have true plugins and settings.

![copyright](https://github.com/BrandonKirbyson/VSCode-Animations/assets/76815699/3588fc3d-4495-4d1c-ad8b-8c9ec0f88625)

yeah, I have installed `Custom CSS and JS Loader` and executed `Animations: install` ` enable` and so on.

I also tried to uninstall and install the plugin, but in vain.

Otherwise, I installed this plugin in Windows yesterday in ` custom css and js loader`  , and it ran perfectly, only with some tiny warnings. But now I install in the same way, and any animation don't work.

----

I'm Chinese and also a freshman in Github, so forgive my broken English, please.
Thanks for your reply!!!

**Comment by BrandonKirbyson** [comment] 2024-01-01 16:30
Ok, thanks for giving helpful information. Did you try using the `Apc Customize UI++` option for the `Install-Method` setting? Let me know if that works.

**Comment by cycode0527** [comment] 2024-01-01 16:48
> Ok, thanks for giving helpful information. Did you try using the `Apc Customize UI++` option for the `Install-Method` setting? Let me know if that works.

thanks much for your reply!

yes，I have tried but it echo an error like "xxx:xxxxxxxxxxxxxxx. permission denied"

I want to give you more info but now is 00:45 with my laptop only 10% electric.

I will (复现）this bug tomorrow.

**Comment by BrandonKirbyson** [comment] 2024-01-01 18:10
Ok, likely the issue is vscode is not running with full permissions which are required for any installation method to properly install the animations.

**Comment by cycode0527** [comment] 2024-01-02 02:51
oh, the error info is like that:
![APC-error](https://github.com/BrandonKirbyson/VSCode-Animations/assets/76815699/5249d02c-bd9e-4520-8390-3a54b9337bf2)

but if I want to start vscode in root-mode , it denied me:

```
root@fedora:~# code
You are trying to start Visual Studio Code as a super user which isn't recommended. If this was intended, please add the argument `--no-sandbox` and specify an alternate user data directory using the `--user-data-dir` argument.
```

**Comment by cycode0527** [comment] 2024-01-02 03:30
If I rename the file showed manually, It will make my vscode broken and I must uninstall it (cry)

**Comment by BrandonKirbyson** [comment] 2024-01-02 04:15
Could this help?

https://stackoverflow.com/questions/38938887/how-to-open-visual-studio-code-with-admin-privileges-to-make-effect-of-the-insta

**Comment by cycode0527** [comment] 2024-01-02 05:03
> Could this help?
> 
> https://stackoverflow.com/questions/38938887/how-to-open-visual-studio-code-with-admin-privileges-to-make-effect-of-the-insta

Thanks very much!!!!!!
I change the ownership of `/usr/share/code` to my user, and change to APC+. Then change the own back. IT WORKS!!

I think this issue can be closed. But I really wonder that why I use `custom js and css` in Windows and `APC+` in linux.........

**Comment by BrandonKirbyson** [comment] 2024-01-02 05:41
Ok great! You could try `custom js and css` again, that has a good chance of working now that `apc` is working. I just initially suggested `apc` because it often works for people when `custom js and css` didn't.

Maybe give `custom css and js` a try again with the same permissions and then I'll close this issue?

**Comment by cycode0527** [comment] 2024-01-02 11:35
> Ok great! You could try `custom js and css` again, that has a good chance of working now that `apc` is working. I just initially suggested `apc` because it often works for people when `custom js and css` didn't.
> 
> Maybe give `custom css and js` a try again with the same permissions and then I'll close this issue?

Thanks, you are right.

I have uninstalled and installed many times to experience, and found that : You must have `w` permission on `/usr/share/code` to install both the plugins. I think that's because your plugin writes something to the dir.

It may have a tiny problem: vscode may display a warning that `Installation appears to be corrupt`. I think it is no matter and set don't show again :smile:

**Comment by BrandonKirbyson** [comment] 2024-01-02 16:13
Ok great, thanks for making this issue because now your helping many people in the future!

This extension uses either `custom css and js` or `apc` to write custom code into vscode's electron html file so that's why permissions are required.

The message `Installation appears to be corrupt` is just `custom css and js`, basically meaning vscode detected custom css, nothing to worry about.

**Closed by BrandonKirbyson** 2024-01-02 16:13 UTC

**Comment by MatthewScholefield** [comment] 2024-03-03 05:51
So to summarize what I had to do:
 1. Temporarily change ownership of VSCode dir: `sudo chown -Rv $USER:$USER /usr/share/code`
 2. Run VSCode and run through all installation steps (uninstall if it was already installed)
 3. Change ownership back to root (for security reasons): `sudo chown -Rv root:root /usr/share/code`

We should probably add this to [the troubleshooting section](https://github.com/BrandonKirbyson/VSCode-Animations?tab=readme-ov-file#troubleshooting).

**Comment by BrandonKirbyson** [comment] 2024-03-03 06:08
Ok, thank you for explaining how. I'll add it soon.
